import { useState } from "react";
import {
  IoCheckmark,
  IoClose,
  IoInformationCircle,
  IoArrowForward,
  IoPricetagOutline,
  IoChevronDown,
} from "react-icons/io5";
import Card from "../common/Card";

// Brand gradient sampled from the product mark (gold → orange → coral).
// Kept as literal hex classes (not composed strings) so Tailwind's JIT
// scanner can find them.
const BRAND = {
  gold: "#F5A623",
  orange: "#F2793D",
  coral: "#F2735E",
};

// Shown only if the ML service hasn't returned real content tips yet
// (still loading, or unreachable) — kept as a visual placeholder, never as
// a silent substitute for real data once it's available.
const fallbackRecommendations = [
  {
    id: 1,
    category: "Video Length",
    current: "Average: 15 minutes",
    recommendation: "8-12 minutes performs best",
    impact: "+25% watch time",
    status: "warning",
  },
  {
    id: 2,
    category: "Thumbnails",
    current: "40% use custom thumbnails",
    recommendation: "Use faces in thumbnails",
    impact: "+200% CTR",
    status: "error",
  },
  {
    id: 3,
    category: "Titles",
    current: "Average 45 characters",
    recommendation: "Use questions or numbers",
    impact: "+35% engagement",
    status: "success",
  },
];

const fallbackTags = [
  "react tutorial",
  "web development",
  "javascript",
  "coding tips",
  "programming",
  "frontend",
  "tech",
  "learn to code",
];

const statusColors = {
  success:
    "bg-success-100 text-success-700 border-success-200 dark:bg-success-900/30 dark:text-success-400 dark:border-success-800",
  warning:
    "bg-[#F5A623]/15 text-[#B8631A] border-[#F5A623]/30 dark:bg-[#F5A623]/15 dark:text-[#F5A623] dark:border-[#F5A623]/30",
  error:
    "bg-error-100 text-error-700 border-error-200 dark:bg-error-900/30 dark:text-error-400 dark:border-error-800",
};

const statusIcons = {
  success: <IoCheckmark className="w-4 h-4" />,
  warning: <IoInformationCircle className="w-4 h-4" />,
  error: <IoClose className="w-4 h-4" />,
};

// Tags collapse to one row by default — a wall of thirty pill buttons reads
// as noise, not signal. "Show all" reveals the rest on demand.
const VISIBLE_TAG_COUNT = 6;

const RecommendationCard = ({ recommendations, suggestedTags, isPlaceholder = false }) => {
  const [tagsExpanded, setTagsExpanded] = useState(false);

  const items =
    recommendations && recommendations.length > 0
      ? recommendations
      : fallbackRecommendations;
  const tags =
    suggestedTags && suggestedTags.length > 0 ? suggestedTags : fallbackTags;
  const visibleTags = tagsExpanded ? tags : tags.slice(0, VISIBLE_TAG_COUNT);
  const hiddenTagCount = tags.length - visibleTags.length;

  return (
    <Card
      title="Content Quality Recommendations"
      subtitle={
        isPlaceholder
          ? "Example data — the recommendation engine is unavailable right now"
          : "AI-powered suggestions, generated by the trained recommendation model"
      }
    >
      <div className="relative">
        {/* Hairline brand-gradient edge */}
        <div
          aria-hidden="true"
          className="absolute -top-4 inset-x-0 h-px bg-gradient-to-r from-transparent via-[#F2793D]/40 to-transparent"
        />

        <div className="space-y-2">
          {items.map((rec, index) => (
            <div
              key={rec.id ?? `${rec.category}-${index}`}
              className="group relative flex items-center gap-3.5 p-3.5 rounded-xl border border-transparent bg-surface-100 dark:bg-dark-surface-light transition-all duration-300 hover:border-[#F2793D]/25 hover:bg-surface-200/70 dark:hover:bg-dark-border overflow-hidden"
            >
              {/* Ambient brand glow on hover */}
              <div
                aria-hidden="true"
                className="pointer-events-none absolute -top-10 -right-10 h-28 w-28 rounded-full bg-[#F2793D]/10 blur-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-500"
              />

              {/* Status Icon */}
              <div
                className={`relative p-2 rounded-lg border flex-shrink-0 ${statusColors[rec.status] || statusColors.warning}`}
              >
                {statusIcons[rec.status] || statusIcons.warning}
              </div>

              {/* Content — one scannable line: what's happening now, an
                  arrow, and what to do instead. The two prose sentences
                  this used to be ("Current: …" / bulb "…") collapse into a
                  single row so the eye doesn't have to re-read the row
                  twice to get the point. */}
              <div className="relative flex-1 min-w-0">
                <div className="flex items-center justify-between gap-3">
                  <h4 className="font-semibold tracking-tight text-text-primary dark:text-dark-text text-sm truncate">
                    {rec.category}
                  </h4>
                  <span
                    className="text-xs font-bold tabular-nums tracking-wide px-2 py-0.5 rounded-full whitespace-nowrap flex-shrink-0"
                    style={{
                      color: BRAND.coral,
                      backgroundColor: `${BRAND.coral}1A`,
                    }}
                  >
                    {rec.impact}
                  </span>
                </div>
                <div className="mt-1 flex items-center gap-1.5 text-sm min-w-0">
                  <span className="text-text-muted dark:text-dark-text-muted truncate">
                    {rec.current}
                  </span>
                  <IoArrowForward
                    className="w-3.5 h-3.5 flex-shrink-0"
                    style={{ color: BRAND.gold }}
                  />
                  <span className="text-text-secondary dark:text-dark-text font-medium truncate">
                    {rec.recommendation}
                  </span>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Tags Suggestions */}
        <div className="mt-5 pt-5 border-t border-surface-300 dark:border-dark-border">
          <h4 className="font-semibold tracking-tight text-text-primary dark:text-dark-text mb-3 flex items-center gap-1.5 text-sm">
            <IoPricetagOutline className="w-4 h-4" style={{ color: BRAND.orange }} />
            Suggested Tags for Your Niche
          </h4>
          <div className="flex flex-wrap gap-2">
            {visibleTags.map((tag, index) => (
              <button
                key={index}
                className="px-3 py-1.5 text-sm font-medium rounded-full border transition-all duration-200 hover:-translate-y-px"
                style={{
                  backgroundImage: `linear-gradient(135deg, ${BRAND.gold}14, ${BRAND.coral}14)`,
                  color: BRAND.orange,
                  borderColor: `${BRAND.orange}40`,
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.backgroundImage = `linear-gradient(135deg, ${BRAND.gold}26, ${BRAND.coral}26)`;
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.backgroundImage = `linear-gradient(135deg, ${BRAND.gold}14, ${BRAND.coral}14)`;
                }}
              >
                {tag}
              </button>
            ))}
            {hiddenTagCount > 0 && (
              <button
                type="button"
                onClick={() => setTagsExpanded(true)}
                className="flex items-center gap-1 px-3 py-1.5 text-sm font-semibold rounded-full border border-dashed border-surface-300 dark:border-dark-border text-text-muted dark:text-dark-text-muted hover:text-text-primary dark:hover:text-dark-text hover:border-surface-400 transition-colors"
              >
                +{hiddenTagCount} more
                <IoChevronDown className="w-3.5 h-3.5" />
              </button>
            )}
          </div>
        </div>
      </div>
    </Card>
  );
};

export default RecommendationCard;
